/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardYieldRouteImport } from './routes/_authenticated/dashboard.yield'
import { Route as AuthenticatedDashboardWeatherRouteImport } from './routes/_authenticated/dashboard.weather'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard.profile'
import { Route as AuthenticatedDashboardMarketRouteImport } from './routes/_authenticated/dashboard.market'
import { Route as AuthenticatedDashboardHistoryRouteImport } from './routes/_authenticated/dashboard.history'
import { Route as AuthenticatedDashboardFertilizerRouteImport } from './routes/_authenticated/dashboard.fertilizer'
import { Route as AuthenticatedDashboardDiseaseRouteImport } from './routes/_authenticated/dashboard.disease'
import { Route as AuthenticatedDashboardChatRouteImport } from './routes/_authenticated/dashboard.chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardYieldRoute =
  AuthenticatedDashboardYieldRouteImport.update({
    id: '/yield',
    path: '/yield',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardWeatherRoute =
  AuthenticatedDashboardWeatherRouteImport.update({
    id: '/weather',
    path: '/weather',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMarketRoute =
  AuthenticatedDashboardMarketRouteImport.update({
    id: '/market',
    path: '/market',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHistoryRoute =
  AuthenticatedDashboardHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFertilizerRoute =
  AuthenticatedDashboardFertilizerRouteImport.update({
    id: '/fertilizer',
    path: '/fertilizer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardDiseaseRoute =
  AuthenticatedDashboardDiseaseRouteImport.update({
    id: '/disease',
    path: '/disease',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatRoute =
  AuthenticatedDashboardChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/dashboard/disease': typeof AuthenticatedDashboardDiseaseRoute
  '/dashboard/fertilizer': typeof AuthenticatedDashboardFertilizerRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/market': typeof AuthenticatedDashboardMarketRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/weather': typeof AuthenticatedDashboardWeatherRoute
  '/dashboard/yield': typeof AuthenticatedDashboardYieldRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/dashboard/disease': typeof AuthenticatedDashboardDiseaseRoute
  '/dashboard/fertilizer': typeof AuthenticatedDashboardFertilizerRoute
  '/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/dashboard/market': typeof AuthenticatedDashboardMarketRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/weather': typeof AuthenticatedDashboardWeatherRoute
  '/dashboard/yield': typeof AuthenticatedDashboardYieldRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/chat': typeof AuthenticatedDashboardChatRoute
  '/_authenticated/dashboard/disease': typeof AuthenticatedDashboardDiseaseRoute
  '/_authenticated/dashboard/fertilizer': typeof AuthenticatedDashboardFertilizerRoute
  '/_authenticated/dashboard/history': typeof AuthenticatedDashboardHistoryRoute
  '/_authenticated/dashboard/market': typeof AuthenticatedDashboardMarketRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/weather': typeof AuthenticatedDashboardWeatherRoute
  '/_authenticated/dashboard/yield': typeof AuthenticatedDashboardYieldRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/chat'
    | '/dashboard/disease'
    | '/dashboard/fertilizer'
    | '/dashboard/history'
    | '/dashboard/market'
    | '/dashboard/profile'
    | '/dashboard/weather'
    | '/dashboard/yield'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/chat'
    | '/dashboard/disease'
    | '/dashboard/fertilizer'
    | '/dashboard/history'
    | '/dashboard/market'
    | '/dashboard/profile'
    | '/dashboard/weather'
    | '/dashboard/yield'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/chat'
    | '/_authenticated/dashboard/disease'
    | '/_authenticated/dashboard/fertilizer'
    | '/_authenticated/dashboard/history'
    | '/_authenticated/dashboard/market'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/weather'
    | '/_authenticated/dashboard/yield'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/yield': {
      id: '/_authenticated/dashboard/yield'
      path: '/yield'
      fullPath: '/dashboard/yield'
      preLoaderRoute: typeof AuthenticatedDashboardYieldRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/weather': {
      id: '/_authenticated/dashboard/weather'
      path: '/weather'
      fullPath: '/dashboard/weather'
      preLoaderRoute: typeof AuthenticatedDashboardWeatherRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/market': {
      id: '/_authenticated/dashboard/market'
      path: '/market'
      fullPath: '/dashboard/market'
      preLoaderRoute: typeof AuthenticatedDashboardMarketRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/history': {
      id: '/_authenticated/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof AuthenticatedDashboardHistoryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/fertilizer': {
      id: '/_authenticated/dashboard/fertilizer'
      path: '/fertilizer'
      fullPath: '/dashboard/fertilizer'
      preLoaderRoute: typeof AuthenticatedDashboardFertilizerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/disease': {
      id: '/_authenticated/dashboard/disease'
      path: '/disease'
      fullPath: '/dashboard/disease'
      preLoaderRoute: typeof AuthenticatedDashboardDiseaseRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chat': {
      id: '/_authenticated/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof AuthenticatedDashboardChatRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardChatRoute: typeof AuthenticatedDashboardChatRoute
  AuthenticatedDashboardDiseaseRoute: typeof AuthenticatedDashboardDiseaseRoute
  AuthenticatedDashboardFertilizerRoute: typeof AuthenticatedDashboardFertilizerRoute
  AuthenticatedDashboardHistoryRoute: typeof AuthenticatedDashboardHistoryRoute
  AuthenticatedDashboardMarketRoute: typeof AuthenticatedDashboardMarketRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardWeatherRoute: typeof AuthenticatedDashboardWeatherRoute
  AuthenticatedDashboardYieldRoute: typeof AuthenticatedDashboardYieldRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardChatRoute: AuthenticatedDashboardChatRoute,
    AuthenticatedDashboardDiseaseRoute: AuthenticatedDashboardDiseaseRoute,
    AuthenticatedDashboardFertilizerRoute:
      AuthenticatedDashboardFertilizerRoute,
    AuthenticatedDashboardHistoryRoute: AuthenticatedDashboardHistoryRoute,
    AuthenticatedDashboardMarketRoute: AuthenticatedDashboardMarketRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardWeatherRoute: AuthenticatedDashboardWeatherRoute,
    AuthenticatedDashboardYieldRoute: AuthenticatedDashboardYieldRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
